### ISSUE TITLE
JsonSchema::AggregateError, Reference resolution over file is not currently supported

### ISSUE THREAD

**Issue by slhck** [thoughtbot/json_matchers#100]
I'm using v0.11.1 with json_schema 0.20.7 in a Rails application, in which I want to validate the response within request specs. I have the helper configured for this root:

```
JsonMatchers.schema_root = "spec/support/schemas"
```

In my request spec I have:

```
expect(json).to match_json_schema("client_api/v1/geolocation_trace")
```

Where the valid JSON content of the response is (compacted for brevity):

```json
{"geolocation_trace":{"id":2,"geolocations":[{"id":10,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":9,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":8,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":7,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":6,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":5,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":4,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":3,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":2,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2},{"id":1,"accuracy":0.0,"client_time":"2019-07-31T13:45:06.000Z","client_time_skewed":"2019-07-31T13:45:06.000Z","latitude":40.1235,"longitude":40.1235,"lonlat":"POINT (40.12345 40.12345)","speed":0.0,"geolocation_trace_id":2}]}}
```

The JSON schemata are as follows:

`spec/support/schemas/client_api/v1/geolocation_trace.json`

```json
{
  "$id": "file:/geolocation_trace.json#",
  "description": "A geolocation trace",
  "type": "object",
  "required": ["id"],
  "definitions": {
    "geolocation": {
      "type": "array",
      "items": {
        "$ref": "file:/geolocation.json#"
      }
    }
  },
  "properties": {
    "id": { "type": "number" },
    "geolocations": {
      "$ref": "#/definitions/geolocation"
    }
  }
}
```

`spec/support/schemas/client_api/v1/geolocation.json`

```json
{
  "$id": "file:/geolocation.json#",
  "description": "A geolocation",
  "type": "object",
  "required": ["id", "latitude", "longitude", "client_time"],
  "properties": {
    "id": { "type": "number" },
    "latitude": { "type": "number" },
    "longitude": { "type": "number" },
    "client_time": { "type": ["string"], "format": "date-time" },
    "client_time_skewed": { "type": ["string", "null"], "format": "date-time" },
    "accuracy": { "type": ["number", "null"] },
    "speed": { "type": ["number", "null"] }
  }
}
```

When running the test, I'm getting:

```
     JsonSchema::AggregateError:
       #/definitions/geolocation/items: Reference resolution over file is not currently supported (URI: file:///geolocation.json). #: Couldn't resolve references: file:///geolocation.json#.
     # /usr/local/bundle/gems/json_schema-0.20.7/lib/json_schema/reference_expander.rb:43:in `expand!'
     # /usr/local/bundle/gems/json_schema-0.20.7/lib/json_schema/schema.rb:208:in `expand_references!'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/matcher.rb:38:in `block in build_and_populate_document_store'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/matcher.rb:38:in `each'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/matcher.rb:38:in `build_and_populate_document_store'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/matcher.rb:9:in `initialize'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/assertion.rb:11:in `new'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/assertion.rb:11:in `initialize'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/rspec.rb:9:in `new'
     # /usr/local/bundle/gems/json_matchers-0.11.1/lib/json_matchers/rspec.rb:9:in `block in <top (required)>'
     # ./spec/requests/client_api/v1/geolocation_traces_spec.rb:57:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:95:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:94:in `block (2 levels) in <top (required)>'
```

But I don't understand why this would not be supported. For all I can tell, `$ref` is explicitly mentioned in the documentation – there's even a test with a relative file reference.

Note that the JSON response is correctly validated with the following schema:

```json
{
  "$id": "file:/geolocation_trace.json#",
  "description": "A geolocation trace",
  "type": "object",
  "required": ["id"],
  "properties": {
    "id": { "type": "number" },
    "geolocations": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "latitude", "longitude", "client_time"],
        "properties": {
          "id": { "type": "number" },
          "latitude": { "type": "number" },
          "longitude": { "type": "number" },
          "client_time": { "type": ["string"], "format": "date-time" },
          "client_time_skewed": { "type": ["string", "null"], "format": "date-time" },
          "accuracy": { "type": ["number", "null"] },
          "speed": { "type": ["number", "null"] }
        }
      }
    }
  }
}
```

**Comment by slhck** [comment]
My thinking was that maybe the relatve paths could not be resolved, but even changing the `schema_root` to `spec/support/schemas/client_api/v1/` does not solve this issue.

**Comment by slhck** [comment]
I realize this might be a problem with `json_schema` itself, but perhaps it's an interaction with this Gem? I'm not sure. I can move the issue if needed, of course.

**Comment by slhck** [comment]
Oh, I got it now. The problem was that I used `$id` instead of `id`, so the file reference could never be resolved. The error was misleading. The fact that the document store was empty never occurred to me.

**Comment by AndKiel** [comment]
I just had the same issue... Looks like the gem is outdated and does not support newer JSON Schema drafts, using draft 6 is mandatory. :(
