### ISSUE TITLE
Array objects returning error

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/json_matchers#23]
Whenever I try to use array objects I keep getting the following error:

```
NoMethodError:
       undefined method `to_sym' for #<Hash:0x007fed4a4a7dd0>
```

Here's my schema:

```json
{
  "type": "array",
  "properties": {
    "id": { "type": "string" },
    "ref_id": { "type": "string" },
    "type": { "type": "string" },
    "channel": { "type": "object" },
    "customer": { "type": ["null", "object"] },
    "sent_by": { "type": ["null", "object"] },
    "notify": { "type": "boolean" },
    "created_at": { "type": "string" },
    "updated_at": { "type": "string" }
  },
  "required": ["id", "ref_id", "type", "channel", "customer", "sent_by", "notify", "created_at", "updated_at"]
}
```

My JSON:

```json
[
  {
    "id": "881aca4e-75c9-11e5-a49f-b74cb0894375",
    "ref_id": "0b8f7afe-4cb0-4a2d-be01-4e826ce8de4e",
    "type": "task",
    "channel": {
      "text": "Hello back!"
    },
    "customer": {
      "id": "8818c078-75c9-11e5-a49f-cb411e8d161b",
      "name": "Anthony Smith",
      "phone_number": "+11932468578",
      "created_at": "2015-10-18T18:53:33.686Z",
      "updated_at": "2015-10-18T18:53:33.686Z"
    },
    "sent_by": {
      "id": "88166120-75c9-11e5-a49f-6f93c6bb584f",
      "name": "Anthony Smith",
      "email": "54@captivatedcustomer.com",
      "photo_url": null,
      "timezone": "Eastern Time (US & Canada)",
      "contact_email": null,
      "notes": null,
      "vcard_url": "/vcards/original/missing.png",
      "account": null,
      "location": null,
      "created_at": "2015-10-18T18:53:33.670Z",
      "updated_at": "2015-10-18T18:53:33.670Z"
    },
    "notify": false,
    "created_at": "2015-10-18T18:53:33.699Z",
    "updated_at": "2015-10-18T18:53:33.699Z"
  }
]
```

This validates using an online validator.

**Comment by anthonator** [comment]
Stack trace:

```
 # ./.gems/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:45:in `block in validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:32:in `select'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:32:in `validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/validator.rb:96:in `block in validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/validator.rb:94:in `each'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/validator.rb:94:in `validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/schema.rb:40:in `validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/validator.rb:225:in `validate'
     # ./.gems/gems/json-schema-2.2.5/lib/json-schema/validator.rb:396:in `validate!'
     # ./.gems/gems/json_matchers-0.4.0/lib/json_matchers/matcher.rb:17:in `matches?'
     # ./.gems/gems/json_matchers-0.4.0/lib/json_matchers/rspec.rb:62:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api/v1/api_v1_messages_spec.rb:23:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:70:in `block (3 levels) in <top (required)>'
     # ./.gems/gems/database_cleaner-1.5.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # ./.gems/gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.gems/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.gems/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.gems/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:69:in `block (2 levels) in <top (required)>'
```

**Comment by seanpdoyle** [comment]
Could you try altering your schema?

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "ref_id": { "type": "string" },
      "type": { "type": "string" },
      "channel": { "type": "object" },
      "customer": { "type": ["null", "object"] },
      "sent_by": { "type": ["null", "object"] },
      "notify": { "type": "boolean" },
      "created_at": { "type": "string" },
      "updated_at": { "type": "string" }
    },
    "required": ["id", "ref_id", "type", "channel", "customer", "sent_by", "notify", "created_at", "updated_at"]
  }
}
```

**Comment by seanpdoyle** [comment]
@anthonator were you able to resolve your issue?

**Comment by anthonator** [comment]
Sorry! Lost track of this. It's been a while and I'm not sure if I ever got this resolved or not. I'm going to close and open back up if I run into this again.

**Comment by anthonator** [comment]
This still doesn't seem to be working for me.
