### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/json_matchers#33]
Seeing a weird error. I keep getting `no implicit conversion of String into Integer` when I believe my JSON and schema match. JSON that doesn't adhere to the schema spits out errors as you'd expect. If I print out `response.body` it looks like valid JSON.

Using Ruby 2.3.0 and Rails 4.2.5.

```
TypeError:
       no implicit conversion of String into Integer
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:9:in `[]'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:9:in `block in validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:6:in `each'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/attributes/properties_v4.rb:6:in `validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:96:in `block in validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:94:in `each'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:94:in `validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/schema.rb:40:in `validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:225:in `validate'
     # /usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:396:in `validate!'
     # /usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/matcher.rb:13:in `matches?'
     # /usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/rspec.rb:62:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api/api_accounts_spec.rb:11:in `block (4 levels) in <top (required)>'
```

**Schema**
```json
{
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "status": { "type": "string" },
    "created_at": { "type": "string" },
    "updated_at": { "type": "string" },
    "user": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "first_name": { "type": "string" },
        "last_name": { "type": "string" },
        "email": { "type": "string" },
        "created_at": { "type": "string" },
        "updated_at": { "type": "string" }
      },
      "required": ["id", "first_name", "last_name", "email", "created_at",
                   "updated_at"]
    },
    "required": ["id", "status", "user", "created_at", "updated_at"]
  }
}
```

**JSON**
```json
{  
  "id":"42107090-c168-11e5-8618-2f9d494c4d2a",
  "status":"active",
  "user":{  
    "id":"42115992-c168-11e5-8618-0b0e87733aad",
    "first_name":"Anthony",
    "last_name":"Smith",
    "email":"16@sticksnleaves.com",
    "created_at":"2016-01-23T00:28:43.385Z",
    "updated_at":"2016-01-23T00:28:43.385Z"
  },
  "created_at":"2016-01-23T00:28:43.379Z",
  "updated_at":"2016-01-23T00:28:43.379Z"
}
```

**Spec**
```ruby
require 'rails_helper'

RSpec.describe "Api::Accounts", type: :request do
  describe "POST /accounts" do
    context 'with valid data' do
      let(:valid_data) { FactoryGirl.attributes_for(:user) }

      it 'should render an account' do
        post accounts_path, valid_data, api_headers

        expect(response).to match_response_schema('account', strict: true)
      end
    end
  end
end
```

**Comment by anthonator** [comment]
Changing the schema attributes around fixed the issue:

```json
{
  "type": "object",
  "required": ["id", "status", "user", "created_at", "updated_at"],
  "properties": {
    "id": { "type": "string" },
    "status": { "type": "string" },
    "created_at": { "type": "string" },
    "updated_at": { "type": "string" },
    "user": {
      "type": "object",
      "required": ["id", "first_name", "last_name", "email", "created_at", "updated_at"],
      "properties": {
        "id": { "type": "string" },
        "first_name": { "type": "string" },
        "last_name": { "type": "string" },
        "email": { "type": "string" },
        "created_at": { "type": "string" },
        "updated_at": { "type": "string" }
      }
    }
  }
}
```
