### ISSUE TITLE
Dependence on json-schema ~> 2.2.5

### ISSUE THREAD

**Issue by iulery** [thoughtbot/json_matchers#35]
Hello,

The json_matchers gem declares a dependence on json-schema ~> 2.2.5, while 2.6.0 is the current version. The json-schema project says they adhere to semantic versioning, so can it please be evaluated whether a newer version of json-schema will work?

Thank you

**Comment by anthonator** [comment]
Yeah, `json_matchers` completely broke for me because `json-schema` is using some deprecated functionality. `json-schema` really needs to be updated.

**Comment by anthonator** [comment]
Updated the `json-schema` version and ran rspec. Had 5 errors.

```
json_matchers_1 | F..FFF.F...
json_matchers_1 | 
json_matchers_1 | Failures:
json_matchers_1 | 
json_matchers_1 |   1) JsonMatchers#match_response_schema fails with an invalid JSON body
json_matchers_1 |      Failure/Error:
json_matchers_1 |        expect {
json_matchers_1 |          expect(response_for("")).to match_response_schema("foo")
json_matchers_1 |        }.to raise_error(JsonMatchers::InvalidSchemaError)
json_matchers_1 | 
json_matchers_1 |        expected JsonMatchers::InvalidSchemaError, got #<JSON::Schema::JsonParseError: 822: unexpected token at ''> with backtrace:
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:426:in `rescue in parse'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:423:in `parse'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/schema/reader.rb:70:in `read'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:545:in `rescue in initialize_schema'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:533:in `initialize_schema'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:53:in `block in initialize'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:53:in `synchronize'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:53:in `initialize'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:259:in `new'
json_matchers_1 |          # /usr/src/bundle/gems/json-schema-2.6.1/lib/json-schema/validator.rb:259:in `validate!'
json_matchers_1 |          # ./lib/json_matchers/matcher.rb:13:in `matches?'
json_matchers_1 |          # ./lib/json_matchers/rspec.rb:62:in `block (2 levels) in <top (required)>'
json_matchers_1 |          # ./spec/json_matchers/match_response_schema_spec.rb:6:in `block (3 levels) in <top (required)>'
json_matchers_1 |          # ./spec/json_matchers/match_response_schema_spec.rb:5:in `block (2 levels) in <top (required)>'
json_matchers_1 |          # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/json_matchers/match_response_schema_spec.rb:5:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 | 
json_matchers_1 |   2) JsonMatchers#match_response_schema accepts options for the validator
json_matchers_1 |      Failure/Error:
json_matchers_1 |        expect(response_for({ "id" => 1, "title" => "bar" })).
json_matchers_1 |          to match_response_schema("foo_schema", strict: false)
json_matchers_1 | 
json_matchers_1 |        expected
json_matchers_1 | 
json_matchers_1 |        {"id":1,"title":"bar"}
json_matchers_1 | 
json_matchers_1 |        to match schema "foo_schema":
json_matchers_1 | 
json_matchers_1 |        {"type":"object","required":["id"],"properties":{"id":{"type":"number"},"title":{"type":"string"}},"additionalProperties":false}
json_matchers_1 | 
json_matchers_1 |        ---
json_matchers_1 | 
json_matchers_1 |        The property '#/' did not contain a required property of 'foo'
json_matchers_1 |      # ./spec/json_matchers/match_response_schema_spec.rb:38:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 | 
json_matchers_1 |   3) JsonMatchers#match_response_schema fails when the body contains a property with the wrong type
json_matchers_1 |      Failure/Error:
json_matchers_1 |        expect(response_for("foo" => 1)).
json_matchers_1 |          not_to match_response_schema("foo_schema")
json_matchers_1 | 
json_matchers_1 |        expected
json_matchers_1 | 
json_matchers_1 |        {"foo":1}
json_matchers_1 | 
json_matchers_1 |        not to match schema "foo_schema":
json_matchers_1 | 
json_matchers_1 |        {"type":"object","properties":{"foo":{"type":"string"}}}
json_matchers_1 | 
json_matchers_1 |        ---
json_matchers_1 |      # ./spec/json_matchers/match_response_schema_spec.rb:50:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 | 
json_matchers_1 |   4) JsonMatchers#match_response_schema contains the body in the failure message
json_matchers_1 |      Failure/Error:
json_matchers_1 |        expect {
json_matchers_1 |          expect(response_for("bar" => 5)).to match_response_schema("foo")
json_matchers_1 |        }.to raise_error(/{"bar":5}/)
json_matchers_1 | 
json_matchers_1 |        expected /{"bar":5}/ but nothing was raised
json_matchers_1 |      # ./spec/json_matchers/match_response_schema_spec.rb:57:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 | 
json_matchers_1 |   5) JsonMatchers#match_response_schema contains the schema in the failure message
json_matchers_1 |      Failure/Error:
json_matchers_1 |        expect {
json_matchers_1 |          expect(response_for("bar" => 5)).to match_response_schema("foo")
json_matchers_1 |        }.to raise_error(/#{schema.to_json}/)
json_matchers_1 | 
json_matchers_1 |        expected /{"type":"array"}/ but nothing was raised
json_matchers_1 |      # ./spec/json_matchers/match_response_schema_spec.rb:74:in `block (2 levels) in <top (required)>'
json_matchers_1 |      # ./spec/support/file_helpers.rb:37:in `block (2 levels) in <top (required)>'
json_matchers_1 | 
json_matchers_1 | Finished in 0.11167 seconds (files took 0.55945 seconds to load)
json_matchers_1 | 11 examples, 5 failures
json_matchers_1 | 
json_matchers_1 | Failed examples:
json_matchers_1 | 
json_matchers_1 | rspec ./spec/json_matchers/match_response_schema_spec.rb:2 # JsonMatchers#match_response_schema fails with an invalid JSON body
json_matchers_1 | rspec ./spec/json_matchers/match_response_schema_spec.rb:25 # JsonMatchers#match_response_schema accepts options for the validator
json_matchers_1 | rspec ./spec/json_matchers/match_response_schema_spec.rb:42 # JsonMatchers#match_response_schema fails when the body contains a property with the wrong type
json_matchers_1 | rspec ./spec/json_matchers/match_response_schema_spec.rb:54 # JsonMatchers#match_response_schema contains the body in the failure message
json_matchers_1 | rspec ./spec/json_matchers/match_response_schema_spec.rb:70 # JsonMatchers#match_response_schema contains the schema in the failure message
json_matchers_1 | 
jsonmatchers_json_matchers_1 exited with code 1
```

**Comment by seanpdoyle** [comment]
@iulery thanks for opening this issue and bringing this to our attention.

@anthonator thanks for taking a stab at the upgrade.

Would you mind opening a PR with your changes so that we can focus on concrete examples of implementation code and try resolving the test failures?

**Comment by atomaka** [comment]
These test failures begin at commit https://github.com/ruby-json-schema/json-schema/commit/00445629320cc8d0c0e8d6269e28bbab26e7e1fb

I did not spend time beyond that debugging the failures.

**Comment by anthonator** [comment]
https://github.com/thoughtbot/json_matchers/pull/37

**Comment by seanpdoyle** [comment]
Closed by https://github.com/thoughtbot/json_matchers/commit/a6d60ffdfe92216cd6147befe368614eb469025f
