### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'json_matchers'

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/json_matchers#36]
This seems to be caused by `json-schema` circa 2.2.5 using some deprecated functionality.

https://github.com/ruby-json-schema/json-schema/blob/53a4f327edefdec284c9e38383be0427d72c12ae/lib/json-schema/validator.rb#L551

`Gem.available?` has been deprecated. As of the latest `bundler` or `rubygems-update` it seems to have been removed.

```
docker-compose run -e RAILS_ENV=test birddog.app rake db:drop db:create db:migrate db:seed
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'json_matchers'.
/usr/src/app/config/application.rb:16:in `<top (required)>'
/usr/src/app/rakefile:4:in `<top (required)>'
NoMethodError: undefined method `available?' for Gem:Module
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:551:in `rescue in <class:Validator>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:546:in `<class:Validator>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:105:in `<module:JSON>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:10:in `<top (required)>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema.rb:21:in `require'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema.rb:21:in `<top (required)>'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/matcher.rb:1:in `require'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/matcher.rb:1:in `<top (required)>'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers.rb:2:in `require'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers.rb:2:in `<top (required)>'
/usr/src/app/config/application.rb:16:in `<top (required)>'
/usr/src/app/rakefile:4:in `<top (required)>'
NoMethodError: undefined method `size' for #<Bundler::SpecSet:0x0055e569a00718>
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:547:in `<class:Validator>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:105:in `<module:JSON>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema/validator.rb:10:in `<top (required)>'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema.rb:21:in `require'
/usr/src/bundle/gems/json-schema-2.2.5/lib/json-schema.rb:21:in `<top (required)>'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/matcher.rb:1:in `require'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers/matcher.rb:1:in `<top (required)>'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers.rb:2:in `require'
/usr/src/bundle/gems/json_matchers-0.5.0/lib/json_matchers.rb:2:in `<top (required)>'
/usr/src/app/config/application.rb:16:in `<top (required)>'
/usr/src/app/rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by seanpdoyle** [comment]
@anthonator thanks for opening this issue and bringing it to our attention.

We'll look into this!

**Comment by atomaka** [comment]
I'm also experiencing the same thing. Upgrading json-schema forcefully can fix the problem.  However, the latest version shows test fails.  These start with https://github.com/ruby-json-schema/json-schema/commit/00445629320cc8d0c0e8d6269e28bbab26e7e1fb for whatever reason.

**Comment by anthonator** [comment]
https://github.com/thoughtbot/json_matchers/pull/37

**Comment by anthonator** [comment]
The test failure turned out to be an issue with how `json-schema` handles caching. I submitted a PR (#37) that fixes the failing tests.

**Comment by seanpdoyle** [comment]
Closed by https://github.com/thoughtbot/json_matchers/commit/a6d60ffdfe92216cd6147befe368614eb469025f
