### ISSUE TITLE
Root level array causes TypeError

### ISSUE THREAD

**Issue by philsturgeon** [thoughtbot/json_matchers#60]
Hey there! I've hit a bit of an issue, and at this time I'm not sure how to fix it. I'll dig in soon, but on the off-chance you're aware of the problem (or anyone else notices things) here it is.

```
  1) Invalidations::IndexController GET /invalidations has a valid contract
     Failure/Error: expect(result).to match_response_schema('invalidations')

     TypeError:
       wrong element type Hash at 0 (expected array)
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/payload.rb:19:in `to_h'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/payload.rb:19:in `extract_json_string'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/payload.rb:4:in `initialize'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/validator.rb:8:in `new'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/validator.rb:8:in `initialize'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/matcher.rb:38:in `new'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/matcher.rb:38:in `build_validator'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/matcher.rb:12:in `matches?'
     # /usr/local/bundle/gems/json_matchers-0.7.1/lib/json_matchers/rspec.rb:72:in `block (2 levels) in <top (required)>'
     # ./spec/requests/invalidations/index_spec.rb:19:in `block (3 levels) in <top (required)>'
```

Standard test:

``` ruby
    it 'has a valid contract' do
      result = JSON.parse(response.body)['result']
      expect(result).to match_response_schema('invalidations')
    end
```

That invalidations file:

```
{
  "type": "array",
  "items": {
    "$ref": "invalidation.json"
  }
}
```

Is this due to the top level object being an array instead of a hash?

**Comment by seanpdoyle** [comment]
Could you pull down https://github.com/thoughtbot/json_matchers/pull/61 and try it out?
