### ISSUE TITLE
TypeError in pretty_json for invalid/unmatching values

### ISSUE THREAD

**Issue by philsturgeon** [thoughtbot/json_matchers#79]
Invalid JSON Schema, or non-matching JSON Schema caused two very confusing errors, which failed to display in any sort of meaningful way.

A new user to JSON Schema wrote this invalid combination of things, which tripped up json_matchers:

```
    "foo": {
      "type": "object",
      "items": {
        "$ref": "./primary-member.json"
       }
    },
```

That will certainly never work, but it didn't trigger any sort of schema error. Instead it showed:
```
     TypeError:
       no implicit conversion of Array into String
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `new'
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:53:in `pretty_json'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:22:in `failure_message'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:76:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api/v3/companies_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
```
 

Then when we made this into valid JSON Schema and fixed that accidental items:
```
    "foo": {
      "$ref": "./primary-member.json"
    },
```
Due to this field value being null, we got:

```
     TypeError:
       no implicit conversion of Array into String
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `new'
     # /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:53:in `pretty_json'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:22:in `failure_message'
     # /usr/local/bundle/gems/json_matchers-0.6.3/lib/json_matchers/rspec.rb:76:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api/v3/companies_controller_spec.rb:82:in `block (4 levels) in <top (required)>'
```

These errors need to be caught, or the code around it should be written more defensively. 

I'll try and dig into the code and fix this, just wanted to get the issue down.

**Comment by seanpdoyle** [comment]
@philsturgeon thanks for opening this issue.

According to the stack trace you've shared, it looks like you're on version 0.6.3` of the gem.

Could you try upgrading to `~> 0.8.0`? There have been [some improvements](https://github.com/thoughtbot/json_matchers/blob/e8b3cc28702a3e6ddef1aea8bb038b9d698e2eac/NEWS.md), including support for Arrays in the response (https://github.com/thoughtbot/json_matchers/issues/60):

```
0.8.0
=====

* Add `assert_json_matches_schema` and `refute_json_matches_schema` for
  use in `minitest` test suites [#66]

[#66]: https://github.com/thoughtbot/json_matchers/pull/66

0.7.3
=====

* Alias `match_response_schema` to `match_json_schema`. These matches can
  validate any JSON, whether it's from a request body, a response body, a Hash,
  or a String. [#68]

[#68]: https://github.com/thoughtbot/json_matchers/pull/68

0.7.2
=====

* Accept Array instances as arguments to `match_response_schema` [#60]

[#60]: https://github.com/thoughtbot/json_matchers/issues/60

0.7.1
=====

* Accept Hash instances as arguments to `match_response_schema` [#58], [#59]

[#58]: https://github.com/thoughtbot/json_matchers/pull/58
[#59]: https://github.com/thoughtbot/json_matchers/pull/59

0.7.0
=====

* Default `record_errors: true` [#52]
* Add support for configuring `record_errors` [#51]

[#52]: https://github.com/thoughtbot/json_matchers/pull/52
[#51]: https://github.com/thoughtbot/json_matchers/pull/51
```

**Comment by philsturgeon** [comment]
Thank you! We were implementing this on ruby 2.3.5 and I expect the grand wizards of dependency resolution picked an older version. I'm sure you nailed it, so I'll close this and open up a new issue if we spot anything else. Thanks for maintaining this amazing library!
